# Generated by Django 4.2.20 on 2026-02-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_payment_transaction_id_alter_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificaterequest',
            name='address',
        ),
        migrations.RemoveField(
            model_name='certificaterequest',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='certificaterequest',
            name='institution_name',
        ),
        migrations.RemoveField(
            model_name='certificaterequest',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='certificaterequest',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='admin_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='certificate_type',
            field=models.CharField(choices=[('Birth', 'Birth Certificate'), ('Marriage', 'Marriage Certificate'), ('Education', 'Educational Certificate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='document',
            field=models.FileField(upload_to='certificates/uploads/'),
        ),
    ]
