# Generated by Django 5.2.8 on 2026-02-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_admin_remarks_certificaterequest_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI/Online')], default='CASH', max_length=10),
        ),
    ]
