# Generated by Django 5.2.8 on 2026-02-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_payment_transaction_id_alter_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verified_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='madrassa_fee',
            field=models.DecimalField(decimal_places=2, default=1200.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='monthly_contribution',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Contribution'), ('MADRASSA', 'Madrassa Fee'), ('ZAKAT', 'Zakat'), ('SADAQAH', 'Sadaqah')], default='MONTHLY', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CARD', 'Card'), ('UPI', 'UPI'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15),
        ),
    ]
