# Generated by Django 5.2.8 on 2026-02-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_payment_month_remove_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('madrassa_fee', models.DecimalField(decimal_places=2, default=1200.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Fee Configuration',
            },
        ),
        migrations.RemoveField(
            model_name='payment',
            name='madrassa_fee',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='monthly_contribution',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
    ]
