# Generated by Django 5.2.8 on 2026-02-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_bookrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_HAND', 'In Hand'), ('RETURNED', 'Returned')], default='PENDING', max_length=20),
        ),
    ]
