# Generated by Django 4.2.20 on 2026-02-23 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_bookrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('disease', models.CharField(max_length=255)),
                ('medicine_details', models.TextField()),
                ('amount_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proof_image', models.ImageField(upload_to='medical_proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
