# Generated by Django 4.2.20 on 2026-02-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_educationprogram_programregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('food_name', models.CharField(max_length=255)),
                ('provider_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
